version: '2'

##############################################################################
# Using: https://pypi.org/project/pypiserver/
##############################################################################

vars:
  GREETING: Pypyserver
  _opts:
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  up:
    desc: starts service
    cmds:
      - docker-compose up $(echo "{{._opts}}")

  # status:
  #   desc: show serveres status
  #   cmds:
  #     - docker-compose ps

  # down:
  #   desc: remove containers
  #   cmds:
  #     - docker-compose down

  # up:
  #   desc: starts containers
  #   cmds:
  #     - docker-compose up $(echo "{{._opts}}")

  # status:
  #   desc: show serveres status
  #   cmds:
  #     - docker-compose ps

  # down:
  #   desc: remove containers
  #   cmds:
  #     - docker-compose down

  data-clean:
    desc: removes contaners mapped data
    cmds:
      - rm -rf packages

  venv-ensure:
    desc: ensures that all packages are preserved
    cmds:
      - pipenv install --skip-lock

  add-mypypi:
    cmds:
      - pipenv install pypiserver --skip-lock
      - mkdir packages

  deps-install:
    cmds:
      - pip install pypiserver

  run-mypypi:
    cmds:
      - pypi-server --overwrite -P .  -a . -p 8081 data/packages

  mypypi-install:
    cmds:
      - |
        pip install --extra-index-url http://localhost:8081 {{._opts}}






