version: '2'

##############################################################################
# Using: https://pypi.org/project/pypiserver/
##############################################################################

vars:
  GREETING: Pypyserver
  _opts:
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  data-clean:
    desc: removes contaners mapped data
    cmds:
      - rm -rf data

  venv-ensure:
    desc: ensures that all packages are preserved
    cmds:
      - pipenv install --skip-lock

  add-mypypi:
    cmds:
      - pipenv install pypiserver --skip-lock

  deps-install:
    cmds:
      - pip install pypiserver

  run-mypypi:
    cmds:
      - pipenv run pypi-server --overwrite -P .  -a . -p 8081 packages

  mypypi-install:
    cmds:
      - |
        pip install --extra-index-url http://localhost:8081 {{._opts}}


  dc-up:
    desc: starts service
    cmds:
      - |
        docker-compose up {{._opts}}

  dc-build:
    desc: build docker container
    cmds:
      - docker-compose build

  dc-status:
    desc: show serveres status
    cmds:
      - docker-compose ps

  dc-down:
    desc: remove containers
    cmds:
      - docker-compose down
